language: cpp
addons:
  apt:
    packages:
    - doxygen
    - graphviz
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen config.dox
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: ./html
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udjgorillaz:$BINTRAY_API_KEY "https://api.bintray.com/content/djgorillaz/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

